import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Next V3 Intro",
  description: "Generated by create next app",
};

const links = [
  {href: '/', label: 'Home'},
  {href: '/docs', label: 'Docs'},
  {href: '/todos', label: 'Todos'},
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <header>
          <nav>
            <ul className="flex items-center">
              {links.map(link => (
                  <li key={link.href}>
                    <Link href={link.href}>{link.label}</Link>
                  </li>
              ))}
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
